site_name: Software Architecture
site_url: !ENV SITE_URL
site_description: Software architecture foundations.
site_author: Rolinda W

repo_url: https://github.com/RolindaW/software-architecture/
edit_uri: 'blob/main/docs/'

# Warning! Subdirectory mapping into NAV section is not (nativelly) supported - pluggin required
nav:
  - Home: index.md
  - Introduction: basics.md
  - MVC:
    - mvc/index.md
    - MVC variantes: mvc/variants.md
  - Layered:
    - Main: layered/README.md
    - MVC variantSSS: layered/other.md
  - About: about.md

theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary

markdown_extensions:
  - toc:
      permalink: true
  #- admonition - TODO: Enable when requried

copyright: Copyright &copy; 2025 <a href="https://github.com/RolindaW">Rolinda W</a>, Maintained by <a href="https://github.com/RolindaW">Rolinda W</a>.
